name: Proxy Hunter

on:
  schedule:
    - cron: '*/15 * * * *' # اجرای خودکار هر 15 دقیقه
  workflow_dispatch: # امکان اجرای دستی توسط مهرداد

jobs:
  build:
    runs-on: ubuntu-latest
    
    # اجازه دادن به گیت‌هاب برای تغییر در فایل‌ها (مثل index.html)
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Libraries
        run: |
          pip install telethon requests

      - name: Run Hunter Bot (5 Minute Session)
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          STRING_SESSION: ${{ secrets.STRING_SESSION }}
        run: python main.py

      - name: Update GitHub Pages (Site)
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "Mehrdad-Hunter-Bot"
          git add index.html
          git commit -m "Update Proxy List and Site" || echo "No changes to commit"
          git push
