name: Hunter Bot Pro
on:
  schedule:
    - cron: '*/15 * * * *' # هر ۱۵ دقیقه
  workflow_dispatch: # قابلیت اجرای دستی

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # اجازه نوشتن برای ذخیره دیتابیس
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install telethon requests

      - name: Run Hunter Agent
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          STRING_SESSION: ${{ secrets.STRING_SESSION }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python main.py

      - name: Save Database Changes
        run: |
          git config --global user.name "Mehrdad-Hunter"
          git config --global user.email "bot@github.com"
          git add hunter_db.json proxies_data.json
          git commit -m "Update Archive [$(date)]" || exit 0
          git push
