name: Update Proxy Archive

on:
  schedule:
    - cron: '0 * * * *' # هر ساعت یکبار
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install
        run: pip install telethon requests

      - name: Run Hunter
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          STRING_SESSION: ${{ secrets.STRING_SESSION }}
        run: python main.py

      - name: Commit and Push
        run: |
          git config --global user.name "MehrdadBot"
          git config --global user.email "bot@github.com"
          git add proxies_data.json
          git commit -m "Update proxy archive" || exit 0
          git push
