name: Run Hunter Bot
on:
  schedule:
    - cron: '0 * * * *' # هر یک ساعت
  workflow_dispatch: # اجرای دستی
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - setup python: uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - install deps: run: pip install telethon requests
      - run bot:
          env:
            API_ID: ${{ secrets.API_ID }}
            API_HASH: ${{ secrets.API_HASH }}
            STRING_SESSION: ${{ secrets.STRING_SESSION }}
          run: python main.py
